
### 1️⃣ Register a new user
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice@example.com",
  "phone": "012345678",
  "password": "123456"
}


### 2️⃣ Login with the registered user to get JWT token

POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "123456"
}

### 3️⃣ Access protected route with the obtained JWT token
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTkwNzE2NjUsImlhdCI6MTc1ODgxMjQ2NSwidXNlcl9pZCI6ImM5NDc0NWJkLTQzNDktNDU0OS1iMWRjLWZlODMzMDY5YzRkZSJ9.FNGTD7gJDdDI4mkyZIYkrlqpJTwz_srIqKp5OBxbPy0
GET http://localhost:8080/api/v1/wallet
Authorization: Bearer {{token}}


### 4️⃣ Deposit money into the wallet
POST http://localhost:8080/api/v1/wallet/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 1000
}


### 5️⃣ Withdraw money to another user
POST http://localhost:8080/api/v1/wallet/withdraw
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 100
}

### 6️⃣ Send Money
POST http://localhost:8080/api/v1/transactions/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "receiver_email": "reciever@example.com",
    "amount": 50
}

### 7️⃣ View Transaction all History
GET http://localhost:8080/api/v1/transactions/histories
Authorization: Bearer {{token}}

### 8️⃣ View Specific Transaction
@transaction_id =ef0103c8-7a95-4f64-a0ce-fc28effbfaee
GET http://localhost:8080/api/v1/transactions/history/{{transaction_id}}
Authorization: Bearer {{token}}